DATA SEGMENT
    ORG 100H
    STR DB 'HELLO WORLD$'
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AL, 48H
    LEA DI, STR
    STD
    SCASB
    MOV AH , 4CH
    INT 21H
CODE ENDS
END START